### PR TITLE
Add multiple=True in sbatch_params for click

### PR DESCRIPTION
**Pull request by zsinx6**
Now it works for spaces too

### CODE REVIEW

**Review by corydodt — APPROVED** [review]

**Comment by corydodt** [comment]
Is there documentation that can be updated here about the option? It's worth mentioning that multiple of the same option are accepted, since that's often confusing to users.

**Comment by zsinx6** [comment]
> Is there documentation that can be updated here about the option? It's worth mentioning that multiple of the same option are accepted, since that's often confusing to users.

What about examples in the README?

**Comment by jamesbeedy** [comment]
> > Is there documentation that can be updated here about the option? It's worth mentioning that multiple of the same option are accepted, since that's often confusing to users.
> 
> What about examples in the README?

👍

**Comment by zsinx6** [comment]
@corydodt @jamesbeedy can you guys check the updated README before the merge?

**Comment by jamesbeedy** [comment]
LGTM 👍 - thank you!

**Comment by corydodt** [comment]
Yeah this is still fine, my approval stands

**Pull request merged**
